# Generated by Django 4.0.6 on 2022-07-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category1',
        ),
    ]
