# Generated by Django 4.0.6 on 2022-07-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_rename_cat_product_category1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category1',
            new_name='category',
        ),
    ]
